FROM sbtscala/scala-sbt:eclipse-temurin-jammy-21.0.1_12_1.9.8_3.3.1 AS builder

WORKDIR /app

# Copy build files
COPY build.sbt .
COPY project project
COPY common common
COPY barista barista

# Build the application
RUN sbt barista/stage

FROM eclipse-temurin:21-jre-jammy

WORKDIR /app

# Copy the staged application
COPY --from=builder /app/barista/target/universal/stage /app

CMD ["/app/bin/barista"]
