FROM sbtscala/scala-sbt:eclipse-temurin-21_2.x AS builder

WORKDIR /app

# Copy build files
COPY build.sbt .
COPY project project
COPY common common
COPY coffeebar coffeebar

# Build the application
RUN sbt coffeeBar/stage && \
    mv $(find target/out -type d -name stage -path '*/coffeebar/universal/stage') /app/stage

FROM eclipse-temurin:21.0.11_10-jre-jammy

WORKDIR /app

# Copy the staged application
COPY --from=builder /app/stage /app

EXPOSE 8080

CMD ["/app/bin/coffeebar"]
