FROM sbtscala/scala-sbt:eclipse-temurin-21_2.x AS builder

WORKDIR /app

# Copy build files
COPY build.sbt .
COPY project project
COPY common common
COPY barista barista

# Build the application
RUN sbt barista/stage && \
    mv $(find target/out -type d -name stage -path '*/barista/universal/stage') /app/stage

FROM eclipse-temurin:21.0.11_10-jre-jammy

WORKDIR /app

# Copy the staged application
COPY --from=builder /app/stage /app

CMD ["/app/bin/barista"]
