FROM sbtscala/scala-sbt:eclipse-temurin-jammy-21.0.1_12_1.9.8_3.3.1 AS builder

WORKDIR /app

# Copy build files
COPY build.sbt .
COPY project project
COPY common common
COPY coffeebar coffeebar

# Build the application
RUN sbt coffeeBar/stage

FROM eclipse-temurin:21-jre-jammy

WORKDIR /app

# Copy the staged application
COPY --from=builder /app/coffeebar/target/universal/stage /app

EXPOSE 8080

CMD ["/app/bin/coffeebar"]
