direction: right
classes: {
  topic: {
    shape: cylinder
    width: 200
    style: {
      fill: lightblue
    }
  }
  box: {
    width: 1500
    label.near: top-left
  }
}

Coffee Bar: {
  label.near: top-left
  Customer: {
    icon: https://icons.terrastruct.com/essentials%2F359-users.svg
  }

  Customer -> API.coffee: browse menu
  Customer -> API.order: place order
  Customer <-> API.check: check order status
  Customer <- API.pickup: pick up order

  API.class: box
  API: {
    grid-rows: 1
    coffee.label: ""
    coffee.box: |md
      GET /coffee
      GET /coffee/:name

      response (list):
      ```
      200 OK — Coffee[]
      ```
      response (single):
      ```
      200 OK — Coffee
      404 Not Found
      ```
    |
    order.label: ""
    order.box: |md
      POST /order  
      ```
      {
        "name": "Alice",
        "coffeeType": "latte"
      }
      ```
      response:
      ```
      202 Accepted
      Location: /check/:orderId
      ```
      ```
      400 Bad Request
      (unknown coffeeType)
      ```
    |
    check.label: ""
    check.box: |md
      GET /check/:orderId

      response (not ready):
      ```
      200 OK
      ```
      response (ready): 
      ```
      303 See Other
      Location: /pickup/:orderId
      ```
    |
    pickup.label: ""
    pickup.box: |md
      GET /pickup/:orderId

      response:
      ```json
      {
        "name": "Alize",
        "coffeeType": "latte",
        "orderId": "..."
      }
      ```
      ```
      200 OK
      404 Not Found
      ```
    |
  }
  Kafka.class: box
  Kafka: {
    label: Kafka Topics
    grid-rows: 1
    order.class: topic
    taken.class: topic
    prepared.class: topic
    ready.class: topic
  }

  Barista.class: box
  Barista: {
    label: Barista Pool
    grid-rows: 1
    takesOrder: Barista takes order
    preparesOrder: Barista prepares order
    announcesReady: Barista announces prepared order
  }

  Kafka.order -> Barista.takesOrder -> Kafka.taken
  Kafka.taken -> Barista.preparesOrder -> Kafka.prepared
  Kafka.prepared -> Barista.announcesReady -> Kafka.ready

  API.order -> Kafka.order
  API.check <- Kafka.ready
  API.pickup <- Kafka.ready
}
